#+title: Francesco's GNU Emacs configuration
#+author: Francesco Scheffczyk
#+property: header-args:emacs-lisp :tangle init.el :results silent

This is my literate Emacs configuration file. From here code blocks are extracted and stored in their respected configuration files. This file is also known as "tangling".

Currently this file tangles all code blocks to the =init.el= file. Later I might switch to a setup where decide on a per code block basis to which file I want to extract to. This could be beneficial if I for example want to keep an =early-init.el= setup in this file as well. For now I want to keep it

* Early configuration

** Lexical Binding
Lexical Binding needs to be enabled for the whole tangled file to prevent compilation warnings. This must be the very first line of the tangled file.

#+begin_src emacs-lisp
  ;;; -*- lexical-binding: t; -*-
#+end_src

** Tangle on Save Hook
This block registers the save hook. It tangles =init.el= so that on the next startup, the hook is re-registered automatically.

#+begin_src emacs-lisp
  (defun fs-tangle-literate-emacs-config ()
    "Tangle the current org file on save."
    (when (string-equal (buffer-file-name)
                        (expand-file-name "~/.config/emacs/config.org"))
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'after-save-hook #'fs-tangle-literate-emacs-config)
#+end_src

* Packages
Here I define all configurations related to extensions and packages.

** Org Mode

*** Base setup
We need to load the package. It is already integrated with Emacs therefore there is no need to download it.

#+begin_src emacs-lisp
  (use-package org
    :ensure nil  ; Org is built-in, so we don't need to download it
    :config
  (setq org-ellipsis " ▾"))
#+end_src

*** Appearance
Changes to the appearance in Org Mode.

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook #'org-indent-mode) ; Indent text below headlines
  (add-hook 'org-mode-hook #'visual-line-mode) ; Wraps lines that are longer then the window
#+end_src

** Completion system
This section configures the completion and fuzzy find system. Multiple packages work here together to create the so-called "minad" stack.

*** Vertico
Vertico is *the UI* and provides a vertical list interface. It is minimal and complies to strictly with built-in Emacs standards.

#+begin_src emacs-lisp
  (use-package vertico
    :ensure t
    :init (vertico-mode))
#+end_src

=savehist-mode= is enabled so Vertico can sort candidates by your usage history.

#+begin_src emacs-lisp
  (use-package savehist
    :ensure nil ; Built-in
    :init (savehist-mode))
#+end_src

*** Orderless
Orderless is the actual *"fuzzy" engine*. It allows me to filter candidates by typing space-seperated components in any order.

With =completion-styles= it is globally declared that orderless is the favoured completion style. basic is a fall back.
A completion style is a backend for completion and it is used by a frontend that provides a completion UI, in this case Vertico.

=completion-catgory-overrides= is used here to define a special case for finding files with =C-x C-f=.
As searching fuzzily into deep subfolders is not possible here, I changed the behaviour here to =partial-completion=.
This allows me to only write partial folder names to navigate to file for example ~/.c/e/con -> ~/.config/emacs/config.org

=orderless-matching-styles= defines a list of styles in which each component of a pattern can match.
=orderless-literal= and =orderless-regexp= are defaults allowing literal and regular expression search.
=orderless-flex= enables the /fuzzy/ search. Characters should appear in that order in the candidate, but not necessarily consecutively.

#+begin_src emacs-lisp
  (use-package orderless
    :ensure t
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles partial-completion))))
    (orderless-matching-styles
     '(orderless-literal
       orderless-regexp
       orderless-flex)))
#+end_src
